namespace LinqExpressionParser.Tests.Generator
{
    public static class ValueParserTestCodeGeneratorHelper
    {
        public const string GeneratedCodeNamespace = "ValueParserTestGenerator.Codes";
        public const string TestClassAttributeName = "ValueParserTestClassAttribute";

        public const string TestDataClassName = "ValueParserTestData";
        public const string TestDataExpected = "Expected";
        public const string TestDataSegment = "Segment";

        public const string AssertMethodAttributeName = "ValueParserAssertMethodAttribute";
        public const string AssertMethodName = "AssertMethod";

        public const string IgnoreDataAttributeName = "IgnoreDataAttribute";

        public const string PostGenerateCodes =
            $$"""
            // <auto-generated/>
            #nullable enable
            using Microsoft.VisualStudio.TestTools.UnitTesting;
            using System.Linq.Expressions;

            namespace {{GeneratedCodeNamespace}}
            {
                [AttributeUsage(AttributeTargets.Class, Inherited = true)]
                public class {{TestClassAttributeName}} : TestClassAttribute
                {
                    public string TestMethodName { get; }
                    public string AssertMethod { get; }

                    public {{TestClassAttributeName}}(string testMethodName, string assertMethod)
                    {
                        TestMethodName = testMethodName;
                        AssertMethod = assertMethod;
                    }
                }

                public class {{TestDataClassName}}<T, V>
                {
                    public Expression<Func<T, V>> {{TestDataExpected}} { get; }
                    public ValueSegment {{TestDataSegment}} { get; }

                    public {{TestDataClassName}}(Expression<Func<T, V>> expected, ValueSegment segment)
                    {
                        {{TestDataExpected}} = expected;
                        {{TestDataSegment}} = segment;
                    }
                }

                [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property)]
                public class {{AssertMethodAttributeName}} : Attribute
                {
                    public string {{AssertMethodName}} { get; }

                    public {{AssertMethodAttributeName}}(string assertMethod)
                    {
                        {{AssertMethodName}} = assertMethod;
                    }
                }

                [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property)]
                public class {{IgnoreDataAttributeName}} : Attribute
                {
                }
            }
            """;
    }
}